import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api, Kpi } from "@/lib/api";
import { CRMLayout } from "@/components/crmlayout.tsx";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { Plus, Edit, Trash, Target } from "lucide-react";
import { useTranslation } from "react-i18next";

export default function Kpis() {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const [isOpen, setIsOpen] = useState(false);
  const [editing, setEditing] = useState<Kpi | null>(null);
  const [code, setCode] = useState("");
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [category, setCategory] = useState("");
  const [targetValue, setTargetValue] = useState(0);
  const [unit, setUnit] = useState("");

  const { data: kpis = [], isLoading } = useQuery({
    queryKey: ["kpis"],
    queryFn: api.hr.kpis.getAll,
  });

  const createMut = useMutation({
    mutationFn: (d: any) => api.hr.kpis.create(d),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["kpis"] }); toast.success(t("hr.statusUpdates.kpiCreated")); setIsOpen(false); resetForm(); },
  });
  const updateMut = useMutation({
    mutationFn: ({ id, d }: { id: number; d: any }) => api.hr.kpis.update(id, d),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["kpis"] }); toast.success(t("hr.statusUpdates.kpiUpdated")); setIsOpen(false); resetForm(); },
  });
  const deleteMut = useMutation({
    mutationFn: (id: number) => api.hr.kpis.delete(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["kpis"] }); toast.success(t("hr.statusUpdates.kpiDeleted")); },
  });

  const resetForm = () => { setEditing(null); setCode(""); setName(""); setDescription(""); setCategory(""); setTargetValue(0); setUnit(""); };

  const handleEdit = (k: Kpi) => {
    setEditing(k); setCode(k.code); setName(k.name); setDescription(k.description || ""); setCategory(k.category || ""); setTargetValue(k.targetValue || 0); setUnit(k.unit || ""); setIsOpen(true);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const payload = { code: editing ? code : undefined, name, description: description || null, category: category || null, targetValue, unit: unit || null };
    if (editing) updateMut.mutate({ id: editing.id, d: payload }); else createMut.mutate(payload);
  };

  return (
    <CRMLayout title={t("hr.kpis.pageTitle")}>
      <div className="flex flex-col gap-6 p-6">
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">{t("hr.kpis.title")}</h1>
            <p className="text-muted-foreground">{t("hr.kpis.description")}</p>
          </div>
          <Dialog open={isOpen} onOpenChange={(o) => { setIsOpen(o); if (!o) resetForm(); }}>
            <DialogTrigger asChild><Button className="gap-2"><Target className="h-4 w-4" /> {t("hr.kpis.actions.create")}</Button></DialogTrigger>
            <DialogContent className="max-w-lg">
              <DialogHeader><DialogTitle>{editing ? t("hr.kpis.dialog.edit") : t("hr.kpis.dialog.create")}</DialogTitle></DialogHeader>
              <form onSubmit={handleSubmit} className="grid grid-cols-2 gap-4 py-4">
                {!editing && (
                  <div className="flex flex-col gap-2 col-span-2">
                    <label className="text-sm font-semibold">{t("hr.kpis.forms.code")}</label>
                    <Input value={code} onChange={(e) => setCode(e.target.value)} placeholder={t("hr.kpis.placeholders.autoGenerated")} className="text-muted-foreground" />
                  </div>
                )}
                <div className="flex flex-col gap-2 col-span-2">
                  <label className="text-sm font-semibold">{t("hr.kpis.forms.name")} *</label>
                  <Input required value={name} onChange={(e) => setName(e.target.value)} placeholder={t("hr.kpis.placeholders.name")} />
                </div>
                <div className="flex flex-col gap-2 col-span-2">
                  <label className="text-sm font-semibold">{t("hr.kpis.forms.description")}</label>
                  <Input value={description} onChange={(e) => setDescription(e.target.value)} />
                </div>
                <div className="flex flex-col gap-2">
                  <label className="text-sm font-semibold">{t("hr.kpis.forms.category")}</label>
                  <Input value={category} onChange={(e) => setCategory(e.target.value)} placeholder={t("hr.kpis.placeholders.category")} />
                </div>
                <div className="flex flex-col gap-2">
                  <label className="text-sm font-semibold">{t("hr.kpis.forms.unit")}</label>
                  <Input value={unit} onChange={(e) => setUnit(e.target.value)} placeholder={t("hr.kpis.placeholders.unit")} />
                </div>
                <div className="flex flex-col gap-2 col-span-2">
                  <label className="text-sm font-semibold">{t("hr.kpis.forms.targetValue")}</label>
                  <Input type="number" step={0.01} value={targetValue} onChange={(e) => setTargetValue(+e.target.value)} />
                </div>
                <div className="col-span-2 flex justify-end gap-2 mt-4">
                  <Button type="button" variant="outline" onClick={() => setIsOpen(false)}>{t("common.cancel")}</Button>
                  <Button type="submit">{t("common.save")}</Button>
                </div>
              </form>
            </DialogContent>
          </Dialog>
        </div>
        <Card className="glass-morphism">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>{t("hr.kpis.table.code")}</TableHead>
                <TableHead>{t("hr.kpis.table.name")}</TableHead>
                <TableHead>{t("hr.kpis.table.category")}</TableHead>
                <TableHead>{t("hr.kpis.table.target")}</TableHead>
                <TableHead>{t("hr.kpis.table.active")}</TableHead>
                <TableHead className="text-right">{t("hr.kpis.table.actions")}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {isLoading ? <TableRow><TableCell colSpan={6} className="text-center py-8">{t("common.loading")}</TableCell></TableRow>
              : kpis.length === 0 ? <TableRow><TableCell colSpan={6} className="text-center py-8">{t("hr.kpis.empty")}</TableCell></TableRow>
              : kpis.map((k) => (
                <TableRow key={k.id}>
                  <TableCell><Badge variant="outline">{k.code}</Badge></TableCell>
                  <TableCell className="font-semibold">{k.name}</TableCell>
                  <TableCell>{k.category || "-"}</TableCell>
                  <TableCell>{k.targetValue != null ? `${k.targetValue} ${k.unit || ""}` : "-"}</TableCell>
                  <TableCell><Badge variant={k.active ? "default" : "secondary"}>{k.active ? t("common.status.active") : t("common.status.inactive")}</Badge></TableCell>
                  <TableCell className="text-right">
                    <Button size="icon" variant="ghost" onClick={() => handleEdit(k)}><Edit className="h-4 w-4" /></Button>
                    <Button size="icon" variant="ghost" onClick={() => deleteMut.mutate(k.id)}><Trash className="h-4 w-4" /></Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Card>
      </div>
    </CRMLayout>
  );
}
