import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api, Position } from "@/lib/api";
import { CRMLayout } from "@/components/crmlayout.tsx";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { Plus, Edit, Trash, Briefcase } from "lucide-react";
import { useTranslation } from "react-i18next";

export default function Positions() {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const [isOpen, setIsOpen] = useState(false);
  const [editingPos, setEditingPos] = useState<Position | null>(null);

  const [code, setCode] = useState("");
  const [title, setTitle] = useState("");
  const [departmentId, setDepartmentId] = useState("");
  const [description, setDescription] = useState("");
  const [status, setStatus] = useState("Active");

  const { data: positions = [], isLoading } = useQuery({
    queryKey: ["positions"],
    queryFn: api.hr.positions.getAll,
  });

  const { data: departments = [] } = useQuery({
    queryKey: ["departments"],
    queryFn: () => api.departments.getAll(),
  });

  const createMutation = useMutation({
    mutationFn: api.hr.positions.create,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["positions"] });
      toast.success(t("hr.statusUpdates.positionCreated"));
      setIsOpen(false);
      resetForm();
    },
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, data }: { id: number; data: any }) => api.hr.positions.update(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["positions"] });
      toast.success(t("hr.statusUpdates.positionUpdated"));
      setIsOpen(false);
      resetForm();
    },
  });

  const deleteMutation = useMutation({
    mutationFn: api.hr.positions.delete,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["positions"] });
      toast.success(t("hr.statusUpdates.positionDeleted"));
    },
  });

  const resetForm = () => {
    setEditingPos(null);
    setCode("");
    setTitle("");
    setDepartmentId("");
    setDescription("");
    setStatus("Active");
  };

  const handleEdit = (pos: Position) => {
    setEditingPos(pos);
    setCode(pos.code);
    setTitle(pos.title);
    setDepartmentId(String(pos.departmentId));
    setDescription(pos.description || "");
    setStatus(pos.status);
    setIsOpen(true);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const payload = {
      code,
      title,
      departmentId: +departmentId,
      description,
      status,
    };

    if (editingPos) {
      updateMutation.mutate({ id: editingPos.id, data: payload });
    } else {
      createMutation.mutate(payload);
    }
  };

  return (
    <CRMLayout title={t("hr.positions.pageTitle")}>
      <div className="flex flex-col gap-6 p-6">
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">{t("hr.positions.title")}</h1>
            <p className="text-muted-foreground">{t("hr.positions.description")}</p>
          </div>
          <Dialog open={isOpen} onOpenChange={(open) => { setIsOpen(open); if (!open) resetForm(); }}>
            <DialogTrigger asChild>
              <Button className="gap-2">
                <Briefcase className="h-4 w-4" /> {t("hr.positions.actions.create")}
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>{editingPos ? t("hr.positions.dialog.edit") : t("hr.positions.dialog.create")}</DialogTitle>
              </DialogHeader>
              <form onSubmit={handleSubmit} className="flex flex-col gap-4 py-4">
                <div className="flex flex-col gap-2">
                  <label className="text-sm font-semibold">{t("hr.positions.forms.code")}</label>
                  <Input
                    readOnly
                    disabled
                    value={editingPos ? code : t("hr.positions.placeholders.autoGenerated")}
                    className="bg-muted text-muted-foreground cursor-not-allowed"
                  />
                </div>
                <div className="flex flex-col gap-2">
                  <label className="text-sm font-semibold">{t("hr.positions.forms.title")} *</label>
                  <Input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder={t("hr.positions.placeholders.title")} />
                </div>
                <div className="flex flex-col gap-2">
                  <label className="text-sm font-semibold">{t("hr.positions.forms.department")} *</label>
                  <Select value={departmentId} onValueChange={setDepartmentId}>
                    <SelectTrigger><SelectValue placeholder={t("hr.positions.placeholders.selectDepartment")} /></SelectTrigger>
                    <SelectContent>
                      {departments.map((d: any) => (
                        <SelectItem key={d.id} value={String(d.id)}>{d.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="flex flex-col gap-2">
                  <label className="text-sm font-semibold">{t("hr.positions.forms.description")}</label>
                  <Input value={description} onChange={(e) => setDescription(e.target.value)} placeholder={t("hr.positions.placeholders.description")} />
                </div>
                <div className="flex flex-col gap-2">
                  <label className="text-sm font-semibold">{t("hr.positions.forms.status")} *</label>
                  <Select value={status} onValueChange={setStatus}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Active">{t("common.status.active")}</SelectItem>
                      <SelectItem value="Inactive">{t("common.status.inactive")}</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="flex justify-end gap-2 mt-4">
                  <Button type="button" variant="outline" onClick={() => setIsOpen(false)}>{t("common.cancel")}</Button>
                  <Button type="submit" disabled={createMutation.isPending || updateMutation.isPending}>{t("common.save")}</Button>
                </div>
              </form>
            </DialogContent>
          </Dialog>
        </div>

        <Card className="glass-morphism">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>{t("hr.positions.table.code")}</TableHead>
                <TableHead>{t("hr.positions.table.title")}</TableHead>
                <TableHead>{t("hr.positions.table.department")}</TableHead>
                <TableHead>{t("hr.positions.table.description")}</TableHead>
                <TableHead>{t("hr.positions.table.status")}</TableHead>
                <TableHead className="text-right">{t("hr.positions.table.actions")}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {isLoading ? (
                <TableRow>
                  <TableCell colSpan={6} className="text-center py-8">{t("hr.positions.loading")}</TableCell>
                </TableRow>
              ) : positions.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={6} className="text-center py-8">{t("hr.positions.empty")}</TableCell>
                </TableRow>
              ) : (
                positions.map((pos) => (
                  <TableRow key={pos.id}>
                    <TableCell className="font-semibold">{pos.code}</TableCell>
                    <TableCell>{pos.title}</TableCell>
                    <TableCell>{pos.department?.name || "-"}</TableCell>
                    <TableCell>{pos.description || "-"}</TableCell>
                    <TableCell>
                      <Badge variant={pos.status === "Active" ? "default" : "secondary"}>
                        {pos.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right">
                      <Button size="icon" variant="ghost" onClick={() => handleEdit(pos)}>
                        <Edit className="h-4 w-4" />
                      </Button>
                      <Button size="icon" variant="ghost" onClick={() => { if (confirm(t("hr.positions.confirmDelete"))) deleteMutation.mutate(pos.id); }}>
                        <Trash className="h-4 w-4 text-red-500" />
                      </Button>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </Card>
      </div>
    </CRMLayout>
  );
}
